name: Preprocessing Workflow

on:
  push:
    branches:
      - main

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas scikit-learn imblearn

      - name: Run preprocessing
        run: |
          python run_preprocessing.py

      - name: Upload preprocessed dataset
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed-data
          path: preprocessing/pima_diabetes_processed/*.csv
