name: Preprocessing Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas scikit-learn imblearn

      - name: Run preprocessing
        run: |
          python run_preprocessing.py

      - name: Upload preprocessed dataset
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed-data
          path: preprocessing/pima_diabetes_processed/*.csv

      - name: Commit & Push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add preprocessing/pima_diabetes_processed/*.csv
          git commit -m "Update preprocessed dataset [skip ci]" || echo "No changes to commit"
          git push origin main
